[pytest]
addopts = --cov=security --cov=scanner_engine --cov-report=term-missing
asyncio_mode = auto
filterwarnings =
    ignore:datetime\.datetime\.utcfromtimestamp\(\) is deprecated:DeprecationWarning:dateutil\.tz\.tz
    ignore:ast\.NameConstant is deprecated and will be removed in Python 3\.14:DeprecationWarning:reportlab\.lib\.rl_safe_eval
    ignore:'crypt' is deprecated and slated for removal in Python 3\.13:DeprecationWarning
    ignore:Accessing argon2\.__version__ is deprecated:DeprecationWarning:passlib\.handlers\.argon2
    ignore:datetime\.datetime\.utcnow\(\) is deprecated and scheduled for removal in a future version:DeprecationWarning:jose\.jwt
